export const dynamicParams = false;
import {notFound} from 'next/navigation';
import Link from 'next/link';
import {developers} from '@/data/developers';
import {projects} from '@/data/projects';
import {properties} from '@/data/properties';
import {PageHero,SectionHeader,PropertyGrid,CTASection,DemoNote,Breadcrumbs} from '@/components/ui';
import {pageMetadata} from '@/lib/seo';
export function generateStaticParams(){return developers.map(({slug})=>({slug}));}
export async function generateMetadata({params}){const {slug}=await params;const d=developers.find(x=>x.slug===slug);return d?pageMetadata(d.name,`Explore illustrative ${d.name} projects, property portfolio and key locations.`,`/developers/${slug}`):{};}
export default async function Page({params}){const {slug}=await params;const d=developers.find(x=>x.slug===slug);if(!d)notFound();const portfolio=properties.filter(x=>x.developerSlug===slug);const related=projects.filter(x=>x.developerSlug===slug);return <><PageHero eyebrow="Developer directory" title={d.name} description={d.description}/><section className="container section"><Breadcrumbs items={[{label:'Developers',href:'/developers'},{label:d.name}]}/><div className="split"><div className="developer-mark">{d.name}<small>OFFICIAL LOGO TO BE ADDED</small></div><div><h2>A closer look at {d.name}.</h2><p>Approved developer background, credentials and project information will be added here. In the meantime, explore the example portfolio to see how the collection connects.</p><DemoNote>No verified partnership claim is made.</DemoNote></div></div></section><section className="section container"><SectionHeader title="Featured projects"/><DemoNote/>{related.length?<PropertyGrid items={related} kind="projects"/>:<div className="empty"><p>Verified projects will be added here.</p><Link href="/projects" className="text-link">Explore all demo projects ↗</Link></div>}</section><section className="section container"><SectionHeader title="Property portfolio"/><PropertyGrid items={portfolio}/></section><section className="section sand"><div className="container split"><div><h2>Key locations</h2><div className="tag-links">{[...new Map(portfolio.map(p=>[p.locationSlug,p])).values()].map(p=><Link href={`/areas/${p.locationSlug}`} key={p.locationSlug}>{p.location} ↗</Link>)}</div></div><div><h2>Keep the full picture in view.</h2><p>Compare project documentation, payment obligations, delivery history and the local context. Developer familiarity is one part of a considered property decision.</p></div></div></section><CTASection title={`Explore ${d.name} with perspective.`} label="Discuss your shortlist" href={`/contact?context=${encodeURIComponent(d.name)}`}/></>}
