import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {properties} from '../data/properties.js';
import {projects} from '../data/projects.js';
import {developers} from '../data/developers.js';
import {locations} from '../data/locations.js';
import {filterListings} from '../lib/discovery.js';
import {validateLead,submitLead} from '../lib/leads.js';
test('demo inventory has valid relationships and local images',()=>{assert.equal(properties.length,18);assert.equal(projects.length,4);for(const items of [properties,projects]){assert.equal(new Set(items.map(x=>x.slug)).size,items.length);for(const p of items){assert(p.demo);assert(developers.some(x=>x.slug===p.developerSlug));assert(locations.some(x=>x.slug===p.locationSlug));for(const image of p.gallery)assert(fs.existsSync(`public${image}`));if(p.paymentPlan.length)assert.equal(p.paymentPlan.reduce((n,x)=>n+x.percent,0),100);}}});
test('combined filters, zero bedrooms, empty results and sorting',()=>{assert.equal(filterListings(properties,{location:'Dubai Creek Harbour'}).length,2);assert.equal(filterListings(properties,{bedrooms:'0'}).length,2);assert.equal(filterListings(properties,{purpose:'Rent',status:'Off-Plan'}).length,0);assert.equal(filterListings(properties,{developer:'Emaar',propertyType:'Apartment'}).length,2);const sorted=filterListings(properties,{},'price-asc');assert(sorted.every((x,i)=>!i||x.price>=sorted[i-1].price));assert(filterListings(projects,{},'featured','Waterfront').every(x=>x.tags.includes('Waterfront')));});
test('enquiries reject invalid input and never claim delivery',async()=>{assert(validateLead({}).email);assert(validateLead({name:'Test',email:'bad',phone:'123',consent:true}).phone);assert.deepEqual(validateLead({name:'Demo Visitor',email:'test@example.com',phone:'+971 500000000',consent:true}),{});assert.deepEqual(await submitLead(),{mode:'demo',delivered:false,stored:false});});
