import HeroSlideshow from '@/components/hero-slideshow';
import Link from 'next/link';
import ScrollToLink from '@/components/ScrollToLink';
import DeveloperPartners from '@/components/DeveloperPartners';
import ProjectCarousel from '@/components/ProjectCarousel';
import {images} from '@/data/images';
import {properties} from '@/data/properties';
import {projects} from '@/data/projects';
import {locations} from '@/data/locations';
import {blog} from '@/data/blog';
import {Photo,Eyebrow,Button,SectionHeader,PropertyGrid,LocationCard,BlogCard,CTASection,DemoNote,ArrowUpRight} from '@/components/ui';
import {PropertySearch} from '@/components/interactive';
import {StorySection,WhySection,ServicesSection,TeamSection,JourneySection,TestimonialsSection} from '@/components/sections';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('Dubai Property. Global Perspective.','Carefully selected projects, transparent advice and personalised guidance from Two Roots Realty.','/');
export default function Home(){return <><section className="home-hero"><HeroSlideshow/><div className="hero-shade"/><div className="container hero-content"><Eyebrow>Dubai real estate · International perspective</Eyebrow><h1>Dubai Property.<br/>Global Perspective.<br/><em>Personal Guidance.</em></h1><p>Carefully selected projects, transparent advice and personalised guidance — from your first enquiry to final handover.</p><div className="actions"><Button href="/projects">Explore Projects</Button><Link className="hero-link" href="/contact"><span>Speak to an Advisor</span> <ArrowUpRight size={14}/></Link></div><div className="hero-bottom"><ScrollToLink targetId="property-search">Discover your next chapter <span aria-hidden="true">↓</span></ScrollToLink><small>Illustrative photography</small></div></div><PropertySearch/></section><DeveloperPartners/><section className="section container"><SectionHeader eyebrow="Selected opportunities" title={<>A place for your <em>next chapter.</em></>} href="/projects" label="View all projects"/><DemoNote/><ProjectCarousel items={projects} kind="projects"/></section><WhySection/><StorySection/><ServicesSection/><section className="section projects-home"><div className="container"><SectionHeader eyebrow="Places taking shape" title="Considered projects. Fresh possibilities." href="/projects" label="Explore projects"/><DemoNote/><ProjectCarousel items={[...projects.slice(2), ...projects.slice(0, 2)]} kind="projects" theme="dark"/></div></section><section className="investment-home section"><div className="container split"><div><Eyebrow>Dubai investment perspective</Eyebrow><h2>See the opportunity.<br/><em>Understand the bigger picture.</em></h2></div><div><p className="lead">A property should fit your ambitions, your timeline and your appetite for risk.</p><p>From payment plans to long-term ownership, we help you ask the right questions and make a more informed decision.</p><Button href="/investment" secondary>Invest with perspective</Button><p className="small">Property values and income can change. Returns are never guaranteed.</p></div></div></section><section className="section container"><SectionHeader eyebrow="Find your Dubai" title="Different places. A world of possibilities." href="/areas" label="Explore all areas"/><div className="locations-grid home-areas">{[locations[0],locations[7],locations[3]].map(x=><LocationCard key={x.id} item={x}/>)}</div></section><TeamSection/><JourneySection/><TestimonialsSection/><section className="section container"><SectionHeader eyebrow="The Two Roots journal" title="A little more perspective." href="/insights" label="All insights"/><div className="blog-grid">{blog.slice(0,3).map(x=><BlogCard item={x} key={x.id}/>)}</div></section><CTASection/></>}
