'use client';
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import Link from 'next/link';
import {Modal,EnquiryForm} from './interactive';
import {ArrowUpRight} from './ui';
const links=[['Home','/'],['About','/about',[['About Two Roots','/about'],['Our Story','/about/our-story'],['Founders & Team','/about/team']]],['Projects','/projects',[['All Projects','/projects'],['Off-Plan','/projects?status=Off-Plan'],['Ready Projects','/projects?status=Ready'],['Investment Opportunities','/investment']]],['Services','/services'],['Developers','/developers'],['Areas','/areas'],['Insights','/insights',[['Blog','/insights'],['Market Insights','/insights?category=Market%20Updates']]],['Contact','/contact']];
export function Wordmark(){return <Link href="/" className="wordmark-img" aria-label="Two Roots Realty home"><img src="/logo.png" alt="Two Roots Realty" className="logo-img" /></Link>}
export { default as Navbar } from './Navbar';

export function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Wordmark/><p>Rooted in relationships.<br/>Connected to opportunity.</p><p className="muted">Dubai, UAE · Established August 2026</p></div><div className="newsletter"><h3>A little more perspective.</h3><p>Property stories and considered insights.</p><EnquiryForm variant="newsletter" submitLabel="Join the newsletter"/></div></div><div className="footer-links"><div><h3>Explore</h3>{[['About','/about'],['Home','/'],['Projects','/projects'],['Services','/services'],['Developers','/developers'],['Areas','/areas']].map(([n,h])=><Link key={n} href={h}>{n}</Link>)}</div><div><h3>Connect</h3>{[['Investment','/investment'],['Insights','/insights'],['Testimonials','/testimonials'],['Contact','/contact'],['Careers','/careers']].map(([n,h])=><Link key={n} href={h}>{n}</Link>)}</div><div><h3>Project types</h3>{['Apartment','Villa','Townhouse','Penthouse','Commercial','Branded Residence'].map(n=><Link key={n} href={`/projects?propertyType=${encodeURIComponent(n)}`}>{n}</Link>)}</div><div><h3>Popular locations</h3>{[['Downtown Dubai','downtown-dubai'],['Dubai Marina','dubai-marina'],['Dubai Hills Estate','dubai-hills-estate'],['Dubai Creek Harbour','dubai-creek-harbour']].map(([n,s])=><Link key={n} href={`/areas/${s}`}>{n}</Link>)}<p>Instagram · LinkedIn<br/>Facebook · YouTube</p><small>[Social URLs to be added]</small></div></div><div className="footer-disclaimer"><p>[Phone number to be added] · [Email address to be added]<br/>[Office address to be added]</p><p>Development preview: all listings and projects are illustrative. Official logo, regulatory registration, advertising permits and authorised partnership credentials are pending client supply. No partnership is implied.</p></div><div className="footer-bottom"><span>© 2026 Two Roots Realty</span><Link href="/privacy-policy">Privacy Policy</Link><Link href="/terms-and-conditions">Terms & Conditions</Link><Link href="/cookie-policy">Cookie Policy</Link></div></div></footer>}
