import Link from 'next/link';
import {Photo,Eyebrow,Button,SectionHeader,ArrowUpRight} from './ui';
import {images} from '@/data/images';
import {team} from '@/data/team';
import {services} from '@/data/services';
import {journey,why} from '@/data/brand';
import {testimonials} from '@/data/testimonials';
export function StorySection(){return <section className="story-section section"><div className="container split"><div className="story-card"><div className="story-card-image-wrap"><Photo src={images.architecture} alt="Dubai architecture, illustrative brand photography" className="story-photo"/><div className="story-card-overlay-badge"><span className="story-badge-dot"></span><span>Our Foundation · Established 2026</span></div></div><div className="story-card-glass-footer"><div className="story-card-highlight"><strong>10+</strong><span>Years of trusted relationship</span></div><div className="story-card-tag">Dubai & Global</div></div></div><div className="story-copy"><Eyebrow>Rooted in friendship. Built on trust.</Eyebrow><h2>Two roots.<br/><em>One vision.</em></h2><p>One hometown in India. Different journeys across the world. A shared vision in Dubai.</p><p>Our story began with a friendship lasting more than a decade. Today, that connection shapes how we help people find their place, and their next opportunity.</p><Button href="/about/our-story" secondary>Discover our story</Button></div></div></section>}
import WhySection from './WhySection';
export { WhySection };
export function ServicesSection(){return <section className="section container"><SectionHeader eyebrow="Guidance that goes further" title="Your property. Our priority." href="/services" label="Our services"/><div className="service-list">{services.map((x,i)=><Link href={`/services#${x.slug}`} key={x.slug}><span className="number">0{i+1}</span><h3>{x.name}</h3><p>{x.description}</p><ArrowUpRight size={18}/></Link>)}</div></section>}
export function TeamSection({full=false}){return <section className="section container"><SectionHeader eyebrow="People behind the perspective" title="A shared vision. Complementary roots." href={full?undefined:'/about/team'} label="Meet the founders"/><div className="team-grid">{team.map(x=><article className="team-card" key={x.id}><div className="portrait-placeholder"><Photo src={x.image || images.portrait} alt="Generic stock portrait placeholder; not a photograph of the founder"/><small>STOCK PLACEHOLDER<br/>NOT THE FOUNDER</small></div><div><h3>{x.name}</h3><p className="eyebrow">{x.role}</p><p>{x.bio}</p>{full&&<ul>{x.expertise.map(y=><li key={y}>{y}</li>)}</ul>}</div></article>)}</div>{full&&<div className="pending-team"><h3>Our wider team</h3><p>Additional team profiles will be added once names, roles and approved photographs are supplied.</p></div>}</section>}
export function JourneySection(){return <section className="section sand"><div className="container"><SectionHeader eyebrow="With you at every step" title="From first conversation to what comes next."/><ol className="journey">{journey.map((x,i)=><li key={x}><span>0{i+1}</span><h3>{x}</h3></li>)}</ol></div></section>}
import TestimonialsSection from './TestimonialsSection';
export { TestimonialsSection };
